libgpgerror: add nativesdk variant
This is a required dependency of enabling a nativesdk pygtk stack

Signed-off-by: Joshua Lock <josh@linux.intel.com>