at 3.1.13: get 'at' depends on 'flex-native' explicitly
'at' needs flex to generate source file lex.yy.c, but it doesn't
depend on flex-native directly; This maybe cause a do_compile
failure if flex-native is not built or included in project.

Error message is:
    error: lex.yy.c: No such file or directory

Get 'at' depends on flex-native to fix this potential issue.

[YOCTO #2919]

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>