bitbake.conf: add BUILDNAME to BB_HASHBASE_WHITELIST
There is an error when "bitbake -S <image>", e.g., core-image-minimal:

NOTE: Reparsing files to collect dependency data
ERROR: Bitbake's cached basehash does not match the one we just generated (/path/to/meta/recipes-core/images/core-image-minimal.bb.do_rootfs)!
ERROR: The mismatched hashes were 730202c9538c4fc1f2e3d1fefa3595f0 and a91bb9451c182e19bfe405ac1bafcc0f

The mismatch can be caused by 2 reasons:

1) BUILDNAME, there is no member of BUILDNAME in the cache when first
   parsing the recipes, it is added by the BBCooker::buildSetVars before
   start the building, so there would be mismatches when compare the
   re-parsed basehash (contains BUILDNAME) to the previous one (no
   BUILDNAME) which is from the cache.

   Add the BUILDNAME to BB_HASHBASE_WHITELIST would fix the problem.

2) DATE or TIME, they are in the cache data and will change when
   re-parsing, move them from BB_HASHCONFIG_WHITELIST to
   BB_HASHBASE_WHITELIST which can be ingored by basehash would fix the
   problem.

   Another fix for DATE or TIME is not to let them expand immediately,
   change: (":=" to "=")
   DATE := "${@time.strftime('%Y%m%d',time.gmtime())}"
   TIME := "${@time.strftime('%H%M%S',time.gmtime())}"

   To:

   DATE = "${@time.strftime('%Y%m%d',time.gmtime())}"
   TIME = "${@time.strftime('%H%M%S',time.gmtime())}"

[YOCTO #3299]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>