gdk-pixbuf: fix the postinstall script failure when no icon is installed
If gtk+ is added to core-image-minimal, postinstall script failed on boot:

Running postinst /etc/rpm-postinsts/104...
gtk-update-icon-cache: No theme index file.
ERROR: postinst /etc/rpm-postinsts/104 failed.

This patch fixed the postinstall script to check for the icon
file first and not run the gtk-update-icon-cache if no icon
is installed.

[YOCTO #2905]

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>