fuse: fix unparsable line due to extra "
Fixes:
ERROR: ParseError at /intel/hmg/new/meta-dlna/meta-guacamayo/recipes-support/fuse/fuse_2.8.6.bb:24: unparsed line: 'RRECOMMENDS_ = "kernel-module-fuse""'
Signed-off-by: Saul Wold <sgw@linux.intel.com>